name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'  # Only trigger when frontend files change

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify frontend files
        run: |
          echo "Checking frontend files..."
          for f in frontend/index.html frontend/script.js frontend/styles.css; do
            if [ ! -f "$f" ]; then
              echo "❌ Missing $f"
              exit 1
            fi
          done
          echo "✅ Frontend files found"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Frontend to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          cd frontend
          vercel --prod --confirm \
            --token=$VERCEL_TOKEN \
            --project=$VERCEL_PROJECT_ID \
            --org=$VERCEL_ORG_ID \
            --prebuilt
