name: Deploy Frontend + Bunny Edge Script

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          vercel deploy --yes --prod \
            --token=$VERCEL_TOKEN \
            --project=$VERCEL_PROJECT_ID \
            --org=$VERCEL_ORG_ID

  bunny-edge-deploy:
    name: Deploy Bunny Edge Script
    runs-on: ubuntu-latest
    needs: frontend-deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Bunny CLI
        run: npm install -g @bunny.net/edgescript-cli

      - name: Deploy Bunny Edge Script
        env:
          BUNNY_SCRIPT_ID: ${{ secrets.BUNNY_SCRIPT_ID }}
          BUNNY_DEPLOYMENT_KEY: ${{ secrets.BUNNY_DEPLOYMENT_KEY }}
        run: |
          edgescript deploy --script-id $BUNNY_SCRIPT_ID --key $BUNNY_DEPLOYMENT_KEY
