name: Deploy IshrealAnime Frontend

on:
  push:
    branches:
      - main  # Deploy when pushing to main
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 3: Deploy static frontend
      - name: Deploy Frontend (Static HTML/CSS/JS)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          vercel --prod --confirm \
            --token=$VERCEL_TOKEN \
            --project=$VERCEL_PROJECT_ID \
            --org=$VERCEL_ORG_ID \
            --prebuilt

  deploy-bunny-script:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      # Step 1: Checkout repo again
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy Bunny Edge Script
      - name: Deploy Bunny Edge Script
        env:
          BUNNY_SCRIPT_ID: ${{ secrets.BUNNY_SCRIPT_ID }}
          BUNNY_DEPLOYMENT_KEY: ${{ secrets.BUNNY_DEPLOYMENT_KEY }}
        run: |
          curl -X POST "https://dash.bunny.net/api/script/deploy" \
            -H "Accept: application/json" \
            -H "AccessKey: $BUNNY_DEPLOYMENT_KEY" \
            -d '{"scriptId":'"$BUNNY_SCRIPT_ID"' }'
